In [1]:
import numpy as np

Let's suppose we want to solve the linear system of equations
$$\begin{align} 10^{-20}x + 2y& =1 \\ x + y &= 1 \end{align}$$

This is equivalent to row reducing the following augmented matrix
$$ A = \begin{bmatrix} 10^{-20} & 2 & 1 \\ 1 & 1 & 1 \end{bmatrix}$$

In [2]:
A = np.matrix([[10**(-20), 2, 1],[1,1,1]])
print(A)

[[1.e-20 2.e+00 1.e+00]
 [1.e+00 1.e+00 1.e+00]]


Let's try to solve this by doing row reduction, telling numpy what to do for each step

We'll start with the top left entry as the pivot

In [3]:
## Multiplying first row by 10^(20) to turn first pivot into 1
A[0,:] = A[0,:]/A[0,0]
print(A)

[[1.e+00 2.e+20 1.e+20]
 [1.e+00 1.e+00 1.e+00]]


In [4]:
## Subtracting second row from first row
A[1,:] = A[1,:] - A[0,:]
print(A)

[[ 1.e+00  2.e+20  1.e+20]
 [ 0.e+00 -2.e+20 -1.e+20]]


In [5]:
## Dividing second row by 2*10^(20) to turn second pivot into 1
A[1,:] = A[1,:]/A[1,1]
print(A)

[[ 1.e+00  2.e+20  1.e+20]
 [-0.e+00  1.e+00  5.e-01]]


In [6]:
## Adding multiple of second row onto first row to cancel out top right entry
A[0,:] = A[0,:] - (A[0,1]/A[1,1])*A[1,:]
print(A)

[[ 1.   0.   0. ]
 [-0.   1.   0.5]]


In [7]:
## Read off answers
print('x = ' + str(A[0,2]))
print('y = ' + str(A[1,2]))

x = 0.0
y = 0.5


The above is quite different from the actual solution of $x = \frac{1}{2-10^{-20}}, \, y = \frac{1-10^{-20}}{2-10^{-20}}$

Fortunately, numpy is smarter than us when choosing its pivots so it avoids this problem by choosing its pivots carefully (typically the pivot with the largest magnitude)

In [8]:
A = np.matrix([[10**(-20), 2],[1,1]])
b = np.matrix([[1],[1]])
sol = np.linalg.solve(A,b)
print('numpy.linalg.solve gets: ')
print('x = ' + str(sol[0]))
print('y = ' + str(sol[1]))

numpy.linalg.solve gets: 
x = [[0.5]]
y = [[0.5]]


Which is the correct solution (up to double-precision floating points)

In [9]:
print('Manually inputting exact solution and then rounding gets: ')
print('x = ' + str(1/(2-10**(-20))))
print('y = ' + str((1-10**(-20))/(2-10**(-20))))

Manually inputting exact solution and then rounding gets: 
x = 0.5
y = 0.5


Note that despite our problems with manually row reducing, the condition number $\kappa(A) = ||A||\cdot||A^{-1}||$ for this example isn't actually that high:

In [10]:
print(np.linalg.cond(A))

2.6180339887498953
